name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flutter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: IRPAY-USER-APP

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Upgrade Flutter dependencies
        run: flutter pub upgrade || true

      - name: Run Flutter tests
        run: flutter test || true

      - name: Analyze Dart code
        run: dart analyze || true
