// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlIsqDqL_eLLRNsj2yTZpaMib1czfoVCU',
    appId: '1:853399373310:android:a6bebba9b8132da09facaf',
    messagingSenderId: '853399373310',
    projectId: 'njangi-6e1ea',
    databaseURL: 'https://njangi-6e1ea-default-rtdb.firebaseio.com',
    storageBucket: 'njangi-6e1ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZtwEipNIWXzL8mgQIE_mi3fMzqpjL1EY',
    appId: '1:853399373310:ios:6d7b2ebbc77efa579facaf',
    messagingSenderId: '853399373310',
    projectId: 'njangi-6e1ea',
    databaseURL: 'https://njangi-6e1ea-default-rtdb.firebaseio.com',
    storageBucket: 'njangi-6e1ea.appspot.com',
    androidClientId:
        '853399373310-1fb536vu7jargtrv73tm13jste9bhr0p.apps.googleusercontent.com',
    iosClientId:
        '853399373310-slujki5ukibt11nij4ktj1cqs301sooa.apps.googleusercontent.com',
    iosBundleId: 'net.appdevs.qrpayuser',
  );
}
