name: qrpay
description: A new Flutter project.
publish_to: "none"

version: 5.0.0+20

environment:
  sdk: ">=3.5.0 <4.2.0"
  flutter: 3.24.0

dependencies:
  flutter:
    sdk: flutter

  get: 4.6.6
  flutter_screenutil: ^5.9.3
  google_fonts: 6.2.1
  country_code_picker: 3.0.0
  get_storage: ^2.1.1
  logger: 2.4.0
  pin_code_fields: 8.0.1
  intl: ^0.19.0
  image_picker: 1.1.2
  dotted_line: 3.2.2
  flutter_svg: 2.0.10
  percent_indicator: ^4.2.3
  qr_code_scanner: ^1.0.1
  flip_card: ^0.7.0
  dotted_border: 2.1.0
  carousel_slider: ^5.0.0
  connectivity_plus: 6.0.5
  flutter_spinkit: ^5.2.1
  awesome_snackbar_content: ^0.1.3
  smooth_page_indicator: ^1.1.0
  country_list_pick: ^1.0.1+1
  intl_phone_field: 3.2.0
  http: 1.2.1
  flutter_inappwebview: 6.0.0

  flutter_html: 3.0.0-beta.2
  share_plus: 7.2.2
  local_auth: 2.3.0
  cached_network_image: 3.3.1
  path_provider: ^2.1.4
  uuid:
  flutter_local_notifications: ^17.2.2
  iconsax: ^0.0.8
  flutter_animate: 4.5.0
  flutter_staggered_animations: ^1.1.1
  qr_flutter: ^4.1.0
  liquid_swipe: ^3.1.0
  pusher_beams: ^1.1.1
  firebase_core: ^3.3.0
  win32: ^5.5.4
  restart_app: ^1.2.1
  r_dotted_line_border: ^0.1.1

dependency_overrides:
  awesome_snackbar_content: 0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_launcher_icons:
  flutter_lints: 3.0.1
  build_runner:
  flutter_gen_runner:
  rename_app: ^1.6.1
  dart_code_metrics: ^4.19.2

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo/app_launcher.png"

flutter_gen:
  output: lib/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: AgencyFB-Bold
      fonts:
        - asset: fonts/AgencyFB-Bold.ttf

  assets:
    - assets/card/
    - assets/clipart/
    - assets/icon/
    - assets/icon/agent.svg
    - assets/logo/
    - assets/qr/
