name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flutter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: IRPAY-USER-APP

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🟢 نصب دقیق Flutter 3.24.4 (پایدارترین نسخه stable در 2025)
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: 'stable'

      - name: Verify Flutter version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Upgrade dependencies
        run: flutter pub upgrade || true

      - name: Analyze code
        run: dart analyze || true

      - name: Run unit tests
        run: flutter test || true
